CREATE DATABASE InPage

CREATE TABLE Genero(
Id VARCHAR(40) PRIMARY KEY,
Nome VARCHAR(100) NOT NULL
);

CREATE TABLE Livro (
Id VARCHAR(40) PRIMARY KEY,
Titulo VARCHAR(100) NOT NULL,
Autor VARCHAR(100) NOT NULL,
IdGenero VARCHAR(40) FOREIGN KEY REFERENCES Genero(Id)
);

CREATE TABLE Usuario(
IdUsuario VARCHAR(40) PRIMARY KEY,
Nome VARCHAR(100) NOT NULL,
Email VARCHAR(256) UNIQUE NOT NULL,
Senha VARCHAR(60) NOT NULL
);

ALTER TABLE Livro
ADD Imagem VARCHAR(255);